ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<p>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<p>',views.cart_remove,name="cart_remove"),
    path('full_remove/<p>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('search',views.search,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
   path('',views.allcategories,name="allcat"),
   path('allproduct/<p>',views.allproducts,name="allproducts"),
   path('detail/<p>',views.detail,name="detail"),
   path('register/',views.register,name="register"),
   path('login',views.user_login,name="login"),
   path('logout',views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)
    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/products',blank=True,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)#one to many relationship
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart
from cart.models import Account,Order



def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)

        for i in cart:
            total+=i.quantity*i.product.price
    except:
        pass
    return render(request,'cart.html',{'c':cart,'total':total})


@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=product)
        if(cart.quantity<cart.product.stock):
          cart.quantity+=1
          cart.save()
    except:
        cart=Cart.objects.create(product=product,user=u,quantity=1)
        cart.save()

    return redirect('cart:cartview')


def cart_remove(request,p):
    product=Product.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=product)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cartview')

def full_remove(request,p):
    product=Product.objects.get(name=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=product)

        cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)

        #total amount
        total=0
        for i in cart:
            total+=i.quantity*i.product.price


        #to check whether user has sifficient money in account
        ac=Account.objects.get(acctnum=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart: #creates record in order table for each object in Cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()
            msg="Order placed successfully"
            return render(request,'orderdetail.html',{'m':msg})
        else:
            msg="Insufficient amount in user account.You cannot place order"
            return render(request,'orderdetail.html',{'m':msg})

    return render(request,'orderform.html')

def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'u':u.username,'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request,'search.html',{'p':product,'query':q})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def detail(request,p):
    product=Product.objects.get(name=p)
    return render(request,'detail.html',{'p':product})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']


        if(p==cp):
            m=User.objects.create_user(username=u,password=p,email=e,)
            m.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("Password not matching")

    return render(request,'register.html')


def user_login(request):
    if(request.method=="POST"):
        name=request.POST['u']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            messages.error(request,"Invalid credentials")
    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Teko:wght@300..700&display=swap" rel="stylesheet">
</head>
<body>

<header>
    <center>
        <img src="{% static 'images/logo.jpg' %}" class="mb-2" height="70px" width="80px">
    </center>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
          {% if user.is_authenticated %}
          {% if user.is_superuser == False %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping" style="font-size:25px;"></i>&nbsp;&nbsp;<sub>{{count}}</sub></a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your orders</a>
        </li>
          {% endif %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">logout</a>
        </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">login</a>
        </li>
          {% endif %}




      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-danger" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
<footer>
    <div class="footer">
        <p><i class="fa-regular fa-copyright"></i>My shop pvt ltd.All rights reserved.</p>
    </div>
</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if not c %}
<div class="container mt-3">
    <h3 class="text-center">Cart is empty</h3>
    <h5 class="text-center"><a href="{% url 'shop:allcat' %}">Continue shopping</a></h5>
</div>

{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">Shopping cart</h4>

    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr><th colspan="6" class="text-center">Cart items</th></tr>
            {% for i in c %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="200px" width="200px"></td>
                <td><b>{{i.product.name}}</b></td>
                <td><b>product id:{{i.product.id}}</b><br>
                    <b>unit price:{{i.product.price}}</b><br>
                    <b>quantity:{{i.quantity}}*{{i.product.price}}</b>
                </td>
                <td>Subtotal:{{i.subtotal}}</td>

                <td>
                    {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-plus" style="font-size:20px;"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                 {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                </td>

            </tr>
            {% endif %}

            {% endfor %}
        </table>
       </div>

    <div class="col-sm-4">
        <table class="table table-bordered">
            <tr><th colspan="4" class="text-center">check out</th></tr>
            <tr><td class="text-center">total:{{total}}</td></tr>

        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-primary">place order</a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-primary">continue shopping</a>
    </div>
</div>
    </div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner.jpg' %}" height="350px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center">Our Collections</h3>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

</div>
<div class="container-fluid" style="margin-bottom:100px;">


    <div class="row">
        {% for i in c %}
        <div class="col-md-4">
            <div class="card">
                 <img src="{{i.image.url}}" class="card-img-top" height="200px" width="50%" alt="...">
                <div class="card-body">
                    <h4 class="card-title text-center">{{i.name}}</h4>
<!--                    <p class="card-text">{{i.desc}} </p>-->

                    <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Products</a>


                </div>

            </div>

        </div>
        {% endfor %}
     {% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-4" style="margin-bottom:100px;">

    <div class="row">
        <div class="col-sm-4"><img src="{{p.image.url}}" height="350px" width="350px"></div>
        <div class="col-sm-5">
            <h4>{{p.name}}</h4>
            <h5>{{p.price}}</h5>
            <p>{{p.desc}}</p>
            {% if user.is_superuser == False %}

            {% if p.stock <= 0 %}
            <h4>Out of stock</h4>
            {% else %}
            <h4><a href="{% url 'cart:addtocart' p.name %}" class="btn btn-secondary">ADD TO CART</a></h4>
            {% endif %}

            {% else %}

            {% if p.stock <= 0 %}
            <h4>Out of stock</h4>

            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary">Add Stock</a></h4>
            {% else %}
            <h4>Product in stock</h4>
            <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary">Add Stock</a></h4>



            {% endif %}
        </div>

    </div>

</div>

{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>login</h1>

<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter The Username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="Enter The Password">
</div>


    <div class="mb-3">

  <input type="submit" class="form-control">
</div>

    </form>

{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
    {% endblock %}


</html>

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5">
    <center>
        <h3 class="text-center text-secondary">{{m}}</h3>
        <h5 class="text-center text-success">Thank you...</h5>
        <h6><a href="% url 'shop:allcat' %">Continue shopping</a></h6>
    </center>
</div>

{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h2>Enter Order Details</h2>
<form method="POST" style="margin-bottom:100px">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a"  placeholder="Enter The Address">
</div>
    <div class="mb-3">
  <label class="form-label">phone number</label>
  <input type="text" class="form-control" name="p"  placeholder="Enter The phone number">
</div>

    <div class="mb-3">
  <label class="form-label">Account number</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Account number">
</div>

     <div class="mb-3">
  <input type="submit" class="form-control">
</div>


    </form>



{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:100px;">
    <h2 class="text-center">Customer name:{{u}}</h2>

    <div class="row">
        {% for i in o %}
        <div class="col-sm-3 my-3 border border1"><img src="{{i.product.image.url}}" height="150px" width="150px"></div>
        <div class="col-sm-7 my-3 border border1">
            <b>Delivery Address:{{i.address}}</b><br>
            <b>Customer phone:{{i.phone}}</b><br>
            <b>Product name:{{i.product.name}}</b><br>
            <b>Product price:{{i.product.price}}</b><br>
            <b>Ordered on:{{i.date_ordered}}</b><br>
            <b>Delivery status:{{i.delivery_status}}</b><br>

        </div>
        {% endfor %}

    </div>

</div>

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="400px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center">{{c.name}}</h3>
    <p>{{c.desc}}</p>

</div>
<div class="container-fluid" style="margin-bottom:100px;">


    <div class="row">
        {% for i in p %}
        <div class="col-md-3">
            <div class="card">
                 <img src="{{i.image.url}}" class="card-img-top" height="200px" width="80%" alt="...">
                <div class="card-body">
                    <h4 class="card-title text-center">{{i.name}}</h4>
                    <h5 class="card-text text-center">{{i.price}} </h5>

                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Details</a>


                </div>

            </div>

        </div>
        {% endfor %}

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<form method="POST" style="margin-bottom:100px">
    {% csrf_token %}


<h1>Register</h1>



<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter The Username">
</div>
    <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="Enter The Password">
</div>

    <div class="mb-3">
  <label class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Confirm password">
</div>
    <div class="mb-3">
  <label class="form-label">email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter email">

</div>
     <div class="mb-3">
  <input type="submit" class="form-control">
</div>


    </form>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="text-center">You have searched for <span class="text-success">{{query}}</span></div>
</center>
<div class="container-fluid" style="margin-bottom:100px;">


    <div class="row">
        {% for i in p %}
        <div class="col-md-3">
            <div class="card" style="margin-bottom:50px;">
                 <img src="{{i.image.url}}" class="card-img-top" height="200px" width="80%" alt="...">
                <div class="card-body">
                    <h4 class="card-title text-center">{{i.name}}</h4>
                    <h5 class="card-text text-center">{{i.price}} </h5>

                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Details</a>


                </div>

            </div>

        </div>
        {% empty %}
        <h4 class="text-center">no search result found</h4>
        {% endfor %}





{% endblock %}